### ISSUE TITLE
Issues AGRIF and XIOS

### ISSUE THREAD

**Issue by malmans2** [immerse-project/wp6.2-demonstrator#37]
@atb299 I tried to run the latest version, but the `AGRIF_QCO` configurations are hanging at the very beginning.
Looks like the cause of the problem is the heavy IO we introduced in `file_def_nemo-{oce,ice}.xml`.  
The same `file_def_nemo-{oce,ice}.xml` work fine without AGRIF (`GLOBAL_QCO`), and `AGRIF_QCO` works fine when we don't write output. Options are:

- There are problems with AGRIF that we need to explore with Jerome
- We need to find the optimal setup for AGRIF runs (i.e., play with `mkslurm` settings)
- Parallel sisters will fix this
- AGRIF doesn't support such a heavy IO and we need to reduce the number of variables we are storing

**Comment by malmans2** [comment]
I'm able to run using different xml files (last week I made a few tests with my regional xml settings).

I've narrowed it down. There is something about the ice variables that is creating problems when using AGRIF.
If I use an empty `file_def_nemo-ice.xml`,  or the [xml I used for my regional runs](https://github.com/NOC-MSM/IMMERSE-overflows/blob/master/runs/GSRIDGE36Zx2/EXP00/file_def_nemo-ice.xml), the model starts. 

So there some issue with AGRIF and [this file](https://github.com/immerse-project/wp6.2-demonstrator/blob/main/cfgs/AGRIF_QCO/GSRIDGE36Zx2-GIBSTRA36Zx2/file_def_nemo-ice.xml) I guess.

**Comment by atb299** [comment]
I removed all the fields after the `<!-- rheology --> ` block and the model runs, so possibly one of the fields in the bottom half of the file. More tests...

**Comment by atb299** [comment]
I'm wondering if we run out of buffer? The slurm output on the jobs that don't run stops at (e.g.):

`-> info : CClientBuffer: allocated 2 x 8804292 bytes for server 11 with a maximum of 4 buffered events
-> info : CClientBuffer: allocated 2 x 16401252 bytes for server 13 with a maximum of 4 buffered events
-> info : CClientBuffer: allocated 2 x 15759156 bytes for server 8 with a maximum of 4 buffered events
-> info : CClientBuffer: allocated 2 x 17200932 bytes for server 10 with a maximum of 4 buffered events`

Seems to be no obvious reason why those later fields should cause a problem. I've tried adding each block in turn, with no success. Other tests are to remove more output and then try adding those later blocks, or to find out how to increase the buffer - I thought it was specified in one of the xml files.

**Comment by atb299** [comment]
I think this might be a bug/issue that arises when there is no ice in the nest domain (i.e. all arrays are 0). Switching the ice off in the GIBSTR nest seems to be the most reliable way of preventing it.
